SECNG-4265 | Fix callback (#143)
* Revert "Fixing 'callback was already called' error obscuring actual diagnostic issue"

This reverts commit 787773cc70d1b9c31157a678c4c5f7b5aa8dce1a.

* bug: Throw errors on table validation errors

Previously, the catch() -> cb(err) -> throw err; chain with database
validation was causing the callback to be called multiple times, causing
issues with startup.

If we throw the error earlier when validating / creating, it's possible
to have that bubble up before the application is initialized, avoiding the
awkward state of "the server is up but the database is not."

```
/app/storage/dynamodb.js:68
    return new Error(
           ^

Error: Mismatched table schema for clever-dev--who-is-who-db-us-west-2-Objects
expected:
{
    "TableName": "clever-dev--who-is-who-db-us-west-2-Objects",
    "AttributeDefinitions": [
        {
            "AttributeName": "_whoid",
            "AttributeType": "S"
        }
    ],
    "KeySchema": [
        {
            "AttributeName": "_whoid",
            "KeyType": "HASH"
        }
    ],
    "ProvisionedThroughput": {
        "ReadCapacityUnits": 1,
        "WriteCapacityUnits": 1
    }
}
actual:
{
    "TableName": "clever-dev--who-is-who-db-us-west-2-Objects",
    "AttributeDefinitions": [
        {
            "AttributeName": "_whoid",
            "AttributeType": "S"
        }
    ],
    "KeySchema": [
        {
            "AttributeName": "_whoid",
            "KeyType": "HASH"
        }
    ],
    "ProvisionedThroughput": {
        "ReadCapacityUnits": 0,
        "WriteCapacityUnits": 0
    }
}
    at checkSchema (/app/storage/dynamodb.js:68:12)
    at /app/storage/dynamodb.js:109:24
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v24.9.0
make: *** [run] Error 1
```

* bug: Coerce 0 to really 0

```
> parseInt(0, 10) || 5;
5
```

We really do want this value to be 0. But JavaScript coerces 0 || 5 to 5, so...

force it to 0.